# Changes here will be overwritten by Copier
_commit: v2.1.0
_src_path: gh:lincc-frameworks/python-project-template
author_email: lincc-frameworks-team@lists.lsst.org
author_name: LINCC Frameworks
create_example_module: false
custom_install: true
enforce_style:
- pylint
- black
- isort
failure_notification:
- slack
include_benchmarks: false
include_docs: false
mypy_type_checking: none
package_name: lf_workflow_dash
project_license: MIT
project_name: lf_workflow_dash
project_organization: lincc-frameworks
python_versions:
- '3.9'
- '3.10'
- '3.11'
test_lowest_version: none
